# Generated by Django 5.2.8 on 2025-11-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crownapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['last_name'], 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
    ]
